# Generated by Django 5.1.3 on 2024-12-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files2', '0003_appfeatures_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appfeatures',
            name='package_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='appfeatures',
            name='prediction',
            field=models.CharField(default='S', max_length=255),
        ),
    ]
